### ISSUE TITLE
[agency] Consider using GEOJSON features

### ISSUE THREAD

**Issue by sebdiem** [CityOfLosAngeles/mobility-data-specification#168]
A few GEOJSON objects are used in the agency API:
- Point in update_vehicle_status and start/end_trip
- MultiPolygon in service_areas

Wouldn't it be more flexible to take advantage of GEOJSON features to enable attaching properties to the GEOJSON object ?
- Point could be replaced by a Feature.
- MultiPolygon could be replaced by a Feature Collection.

This would enable, for instance, attaching a pricing rate as a property to the geometry of a service_area. Or attach the accuracy to the location.

What do you think ?

**Comment by hunterowens** [comment]
@sebdiem this seems like a good idea! I'm wrapping it with #169, which would add JSON Schema support in agency and as something to target for the 0.3.0 release.

**Comment by karcass** [comment]
See recent changes and updates to agency.  GeoJSON has largely been eliminated, because posting the entire route has been eliminated.  GeoJSON is not applicable for vehicle registration, and does not add anything useful for events or telemetry.

The service_areas endpoint will use GeoJSON to match provider.

**Comment by oderby** [comment]
Should we close this issue now @hunterowens? Per @karcass comment above, this doesn't seem relevant anymore.

**Comment by toddapetersen** [comment]
Agree with @oderby.  No longer relevant with updated agency.
