### ISSUE TITLE
No identifier specified for `status_changes` entities

### ISSUE THREAD

**Issue by ezheidtmann** [CityOfLosAngeles/mobility-data-specification#191]
Status change entities don't currently have an identifier, so it's not clear how consumers should de-duplicate these entities.

**Comment by thekaveman** [comment]
I've been operating under the assumption that the combination of `(provider_id, device_id, event_time)` is always unique.

In other words, there can never be simultaneous events for a single device from a given provider (no matter how small the difference in time between subsequent events).

Does this make sense from a practical/real-world point of view?

**Comment by ezheidtmann** [comment]
Seems like a reasonable assumption if `event_time` is unlimited precision, but providers aren't required to expose subsecond resolution. In my dev environment containing real data, about 10% of events would be considered duplicates by that metric.

Currently `(provider_id, device_id, event_time, event_type)` is unique across my small sample size. But I've seen one provider returning exact duplicate events (all fields identical!) within the same page, so strictly speaking even that isn't unique.

In my opinion, the spec should either require uniqueness across some list of fields, or require providers to assign a `uuid` to each status change entity.

**Comment by oderby** [comment]
I agree with @ezheidtmann - I think it's becoming clear that the spec will need to do something to clarify expectations here. Aside from real-world duplicates (occurring both mistakenly and for real-use cases), some providers have started intentionally reporting simultaneous events to capture state transitions not currently designed/supported in the spec (see https://github.com/CityOfLosAngeles/mobility-data-specification/issues/214#issuecomment-457891401).

I have a strong preference to require status_change events be reported with a UUID over relying on a composite primary key. It's simpler, and separates the concern of managing/indexing data from reporting real-world data honestly. I'll put up a PR soon.

**Comment by hyperknot** [comment]
This is a critical question, as while duplicate trips are non-existent in trips streams, most providers have a very large number of duplicate events in their status change streams (up to 1000 duplicates per day). 

The reason is very simple, they can use trip_id as a primary key in their backend, while there is no such thing for status changes right now.

I strongly recommend requiring a UUID for `event_id` in the specs, exactly like we do it for `trip_id`.

// Calculation was based on comparing the MD5 hash of the JSONs of the events, which means that all columns were checked.

**Comment by oderby** [comment]
Opened https://github.com/CityOfLosAngeles/mobility-data-specification/pull/225 to address this.

**Comment by karcass** [comment]
I would expect (device_id, event_time, event_type) to be unique as discussed, and any non-unique tuples would be de-duped trivially.  The reference implementation of `agency` has those fields as a composite primary key, so the db prevents storing duplicates. 

This feels like a debugging tool for provider implementation mistakes rather than a needed feature.  I would rather specify composite uniqueness than add another field.

**Comment by asadowns** [comment]
I agree with @ezheidtmann @oderby and @hyperknot . Having any sort of uniqueness constraint that requires computation even if the result is ultimately the same requires knowledge of the internal system and requires assumptions about the constraints. It does not seem burdensome to require a UUID. I think #225 is a sensible suggestion.

That being said, the UUID approach will become a burden if assumptions are made about the value of that UUID over time since records will need to be reconciled in some cases after the fact. Depending on the implementation of the underlying systems and the internal storage of the data in the providers' system the need to update a record seems burdensome. UUIDs should be considered a unique identifier for that event in a particular API request rather than a persistent identifier for that event over time.

**Comment by karcass** [comment]
> UUIDs should be considered a unique identifier for that event in a particular API request rather than a persistent identifier for that event over time.

I am not following the rationale.  How can you use an event UUID for de-duping if the same event can have different UUIDs in different contexts?

**Comment by thekaveman** [comment]
I am in agreement with @karcass here, I'd rather see Status Change uniqueness defined from the current fields vs. a new field. 

I like the idea of including `event_type` and `event_type_reason` in the uniqueness constraint, to account for e.g. a `low_battery` event occurring at the same time as a `user_drop_off`.

The addition of `event_type` could help protect against future changes to the reasons.

> .... there can never be simultaneous events for a single device from a given provider

It just doesn't make sense for multiple e.g. `user_drop_off` to occur to the same device at the same time. This data is supposed to represent actual events that occurred in the real physical world.

**Comment by lionel-panhaleux** [comment]
I find asking for a (provider, device, timestamp) unicity makes sense: if a single provider presents multiple changes at the same timestamp, there is no way to order them and deduce the final vehicle state, this would be a serious flaw.

Moreover, asking an UUID does not make it stable across the API. As @asadowns stated, it would be fine for a provider to present an event at some point in time with a given UUID, an another UUID when queried two weeks later.

Finally, the UUID would need to be the same on the Agency side of things to allow for proper de-duplication : using the event timestamp feels like a more simple way, see for example #272 and attached PR #273.

**Comment by karcass** [comment]
Based on the lack of clear benefit beyond (provider_id, device_id, timestamp), I propose that we close this.

**Comment by hunterowens** [comment]
agreed. closing.
