### ISSUE TITLE
Agency does not ingest some trip details required by Provider

### ISSUE THREAD

**Issue by karcass** [CityOfLosAngeles/mobility-data-specification#253]
An implementation of Agency should be able to ingest all necessary data to fully implement Provider.  Agency currently has _most_ of that information, but it does not receive `standard_cost`, `actual_cost`, or `trip_distance`.  Distance could be derived from the GPS trace, but the other two cannot. 

I was thinking that we could add the cost fields as required for the `trip_end` event.

Interested to hear what folks think.

**Comment by hunterowens** [comment]
Honestly, this sounds like something that will forever live in provider. Providers might not have calculated cost by trip end end, or they could charge an additional fee for parking in a zone that isn't prioritized, etc. Since providers remain source of truth on cost, I recommend that it doesn't move to agency. 

_eg_ call to trip -> in prohibited zone -> trip is still ended -> fee imposed.
