### ISSUE TITLE
Add event_type_reason codes to provider status_changes API

### ISSUE THREAD

**Issue by margodawes** [CityOfLosAngeles/mobility-data-specification#278]
Seattle DOT requires vendors to provide an administrative unlock functionality to allow city staff to unlock and move an improperly parked bike if needed. It would be helpful to include the following associated event_type_reason codes for tracking any use of the administrative unlock: “admin_pick_up” and “admin_drop_off_unavail” to the event_type “unavailable” and “admin_drop_off_avail” to the event_type “available.”

**Comment by karcass** [comment]
@margodawes Agency has an event_type of `city_pick_up` but not (yet) `city_drop_off`.  We can definitely add your two recommended flavors of drop-off on the Agency side.  I like your use of `admin` more than `city` because it may be a regional transit provider, not necessarily a city.  

Can you give some color on how administrative lock/unlock works from your perspective?  Seems like that could be formally moved into a Provider endpoint.

**Comment by hunterowens** [comment]
@margodawes Quick question - when Seattle DOT unlocks a bike, it is done via some sort of app based mechanism or do you physically pick up / remove the device? 

If it is app based, then the providers should have knowledge of which devices where unlocked via the admin app for 

If it isn't app based, it might be hard for providers to know which vehicles were moved by the city since it wouldn't be registered in a system. 

If it is done via app, I can make a PR for this.

**Comment by hunterowens** [comment]
some off thread emails, but it sounds like this feature hasn't been launched yet in SEA. However, all the options they are some sort of solution where provider receives notification from the city that they would like to initiate a unlock, so I think we should add this in. I'll prep a  PR targeting this shortly.

**Comment by hunterowens** [comment]
might make sense to standardize on either `city` or `agency` as the term, as `admin` is unclear.
