### ISSUE TITLE
Clarification: do trips / status changes need to be sorted?

### ISSUE THREAD

**Issue by yoimnik** [CityOfLosAngeles/mobility-data-specification#305]
Do the Trips and Status Changes Provider API responses need to be sorted by event time? I don't see anywhere in the spec where it requires that, but I just wanted to make sure this wasn't an implied requirement from client usage of the Provider endpoints.

**Comment by yoimnik** [comment]
Similarly, do the `route` points in the Trips body need to be sorted by time as well?

I've been using https://github.com/CityofSantaMonica/mds-provider-services/ as a reference to see generally how provider data is analyzed, and it seems that mds-provider-services does its own sorting of all status changes, trips, and routepoints.

But my question still stands -- do the status changes, trips, and route points within trips need to be sorted by event time from the API response?

**Comment by yoimnik** [comment]
@rf- Curious what your team does for this

**Comment by dyakovlev** [comment]
In the current API definition, trips and status changes are not specified to be ordered in any sort of meaningful way. Both response sets have an implied total ordering due to attached timestamps.

Regarding route points within trips - the spec is once again nonspecific, but we've seen situations where the points are definitely not ordered. Due to this, our ingestion code applies an ordering to the route points as a precaution. It would be nice if we didn't have to, but I don't know if we'll ever be able to remove that sort.

**Comment by thekaveman** [comment]
I think this was at least partially addressed by #301 right? (With the answer being, _yes_)

**Comment by hunterowens** [comment]
yeah, I think so. closing. (all- let me know if I'm wrong here/ am missing something)
