### ISSUE TITLE
State machine clarification

### ISSUE THREAD

**Issue by patata3000** [CityOfLosAngeles/mobility-data-specification#343]
The state machine puts status in inactive from available and unavailable after a city_pickup but the table says it should go to removed. I believe it should be removed but I want to make sure.

On this subject btw, I would have 2 states: one would be "handled by city" and the other one would be "handled by provider" which have 2 different semantics for the agency. I understand the will to keep the state machine simple but I believe it should reflect the reality with no ambiguity. In this case, an agency may want to know who's having the vehicle without checking the events.

Moreover, provider_drop_off may put the state into unavailable, decoupling the status of a vehicle being in the street from being available to user. And provider_pick_up may only be coming from unavailable. This could be one use case of compound events talked about in #274 .

I wish there were a more precise definition of the states. e.g.: What does `inactive` mean exactly? Does it comprise all the vehicles that just registered or the ones that didn't send a signal for (for example) a week? Should there be a time limit after which a provider must consider a vehicle to be `inactive`?

I don't know all the details of mds yet so I probably overlooked a lot of stuff but I still want your opinion on these.

**Comment by karcass** [comment]
In practice I don't think anyone is currently using `city_pickup`, because there is currently no mechanism for an agency (city etc.) to communicate a city-driven status_change.

To answer your question about `inactive`, that status (currently) has the very broad meaning of "not in the public right of way but also not in a provider's possession".  This includes short term "recently went missing but hopefully will be recovered" and long-term "missing for over a month, or definitely destroyed or recycled".

It is up to providers to identify vehicles that they believe to be out of the PROW, but not in their possession, and send the appropriate `deregister` event.  Generally this is established by internal criteria, e.g. using lack of GPS signal, or attempting a `provider_pick_up` where the device is not where it last reported.  It's a given that this will be an imperfect measurement, but the idea is to aim for roughly the same number of false-positives and false negatives so that (e.g.) cap counting is _truthy_.

Whether to split this into two states (short-term and long-term) is up for debate.  Generally I am resistant to status proliferation unless backed by strong use-cases.
