### ISSUE TITLE
Telemetry only for trips

### ISSUE THREAD

**Issue by patata3000** [CityOfLosAngeles/mobility-data-specification#344]
Ok so I'm asking this but I may have misunderstood some things.
Why do we restrict telemetry only for trips? It seems that for dockless share vehicle, they can be moving outside of trips. Shouldn't mds add some rules for telemetry for a vehicle moving outside a trip?

**Comment by patata3000** [comment]
More on `/telemetry` is that I don't get the point of it. There is no trip id in it and it only applies for trips. I still may have misunderstood some things.

**Comment by karcass** [comment]
In Provider, telemetry is explicitly associated with `trips` and `status_changes` (each status change includes an `event_location`).  

Agency keeps the same tight linkage between `events` (which are basically the same thing as `status_changes`).  

Agency's `/telemetry` endpoint is less specific about linking telemetry to trips (or not).  Cities can set policy to require providers to send GPS data _just_ for trips/events, or based on _any_ movement, or any ask supported by use cases.  Cities can specify GPS reporting latency and frequency, and which events require GPS locations and which do not.  These policies are explicitly outside of the MDS spec, because it is variable by jurisdiction.  To the extent that there are references in the current GPS spec to either frequency of latency of GPS reporting, those references are going to be removed in 0.4.0.

To reconstruct a trip route, you don't need each telemetry item to have a trip_id, all you need is an accurate timestamp paired with `start_trip` and `end_trip` events.  Then you query the telemetry database to get all GPS points between the timestamp of the start and end events.

**Comment by patata3000** [comment]
Alright thanks! It helps a lot!
