### ISSUE TITLE
Clarification of `associated_trips` in Provider API Status Changes endpoint?

### ISSUE THREAD

**Issue by oderby** [CityOfLosAngeles/mobility-data-specification#88]
I'm curious to hear more about the `associated_trips` field in a status change. My questions are:
* Why/when would a single reservation event have multiple trips related to it?
* What additional information does this field provide that you couldn't determine by joining with trips on device_id and event_time?

**Comment by thekaveman** [comment]
I'm reopening this issue because I'm not convinced it was adequately solved, as @oderby points out. 

Is there a case where multiple values should show up in this array? I don't quite understand that yet. If not, can we add to `0.2.1` and make this an optional `UUID` as suggested by @oderby. It's no more breaking in my mind than #146, which has already been slated for inclusion...

**Comment by black-tea** [comment]
I have seen a provider add data into this field (when it applies). However, I have never seen two trip IDs for that field and I am not sure the circumstances we would see more than one.

**Comment by black-tea** [comment]
@hunterowens One additional clarification question: Right now, under the Required/Optional, the field is listed as "Optional based `event_type_reason`". Would a provider be in compliance if it never provided the `associated_trips` field? 

My understanding is that the field is required for user-generated event types? If so, would it be more clear to be listed as 'Required if applicable based on `event_type_reason`', with the requirement being any user-generated `event_type`? Or perhaps I am mistaken?

**Comment by hunterowens** [comment]
Closed with #217
